export default function getObject(){
  return {
    id: 0,
    parent_id:0,
    related_id: 0,
    company_id: 0,
    title: '',
    address: '',
    desc: '',
    content: '',
    owner_id: 0,
    code: '',
    phone: '',
    mobile: '',
    location_id: 0,
    type: 0,
    images: [],
    contacts: [],
    conpany: {
      id: 0,
      name: '',
      code: '',
      fullname: '',
      title: '',
      address: '',
      location_id: 0,
      geography_lon: 0,
      geography_lat: 0,
      detail_id: 0,
      parent_id: 0,
      desc: '',
      content: ''
    },
    contact: {
      id: 0,
      name: '',
      realName: '',
      IDCard: '',
      companyName: '',
      company_id: 0,
      department: '',
      email: '',
      address: '',
      location_id: 0,
      geography_lon: 0,
      geography_lat: 0,
      detail_id: 0,
      parent_id: 0,
      desc: '',
      content: ''
    }
  }
}