export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const GET_CONTENT_LIST = 'GET_CONTENT_LIST'
export const GET_CONTENT_LIST_FAILURE = 'GET_CONTENT_LIST_FAILURE'

export const UPDATE_HEADLINE = 'UPDATE_HEADLINE'
export const GET_HEADLINE = 'GET_HEADLINE'

export const GET_ARTICLE = 'GET_ARTICLE'
export const GET_ARTICLE_FAILURE = 'GET_ARTICLE_FAILURE'
export const CLEAR_ARTICLE = 'CLEAR_ARTIVLE'

export const GET_TAGS = 'GET_TAGS'
export const GET_TAGS_FAILURE = 'GET_TAGS_FAILURE'

export const GET_TAG_CONTENT_LIST = 'GET_TAG_CONTENT_LIST'
export const GET_TAG_CONTENT_LIST_FAILURE = 'GET_TAG_CONTENT_LIST_FAILURE'

export const GET_COMMENTS_LIST = 'GET_COMMENTS_LIST'
export const GET_COMMENTS_LIST_FAILURE = 'GET_COMMENTS_LIST_FAILURE'

export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const SUBMIT_COMMENT_FAILURE = 'SUBMIT_COMMENT_FAILURE'

// #############

export const LOADING = 'LOADING'

// 产品
export const GET_PRODUCT_DOOR = 'GET_PRODUCT_DOOR';
export const GET_PRODUCT_DOORS = 'GET_PRODUCT_DOORS';

export const GET_PRODUCT_TAG = 'GET_PRODUCT_TAG';
export const DELETE_PRODUCT_TAG = 'DELETE_PRODUCT_TAG';
export const GET_PRODUCT_TAGS = 'GET_PRODUCT_TAGS';

export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY';
export const GET_PRODUCT_CATEGORYS = 'GET_PRODUCT_CATEGORYS';

export const GET_USER_USER = 'GET_USER_USER';
export const GET_USER_TOKEN = 'GET_USER_TOKEN';
export const GET_USER_MESSAGE = 'GET_USER_MESSAGE';
